name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Firefox
      run: sudo apt-get install firefox
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/checkout@v2
    - name: Install package and dependencies
      run: npm i
    - name: Run tests
      run: npm test
      env:
        CI: true
